import { notFound } from "next/navigation";
import Link from "next/link";
import { AdminNav } from "@/components/admin/admin-nav";
import { AccessEditor, DeliveryRetry, MemberDataControls } from "@/components/admin/governance-controls";
export default function PreviewAdmin() {
  if (process.env.NODE_ENV === "production") notFound();
  return <div className="admin-workspace"><aside className="admin-sidebar"><AdminNav /></aside><div className="admin-workspace-content"><header className="admin-mobile-bar"><p className="font-bold text-mist">Sanchari Ops</p><p className="text-xs text-lichen">Organiser workspace</p></header><main id="main" className="mobile-glass-screen container space-y-8 py-12"><div className="rounded-panel border border-ridge bg-basalt p-7"><p className="text-xs uppercase tracking-[.2em] text-signal">Sanchari · Control room</p><h1 className="mt-3 text-3xl font-bold md:text-5xl">The people behind every journey.</h1><p className="mt-4 max-w-2xl text-lichen">Staff permissions, a clear history of changes, considerate communication and member care.</p><p className="mt-4 text-xs text-signal">Local design preview · sample records only. Saving requires authorised access and real records.</p></div>
    <nav className="flex flex-wrap gap-3 text-sm">{[["#access","Staff access"],["#activity","Activity"],["#delivery","Notifications"],["#analytics","Analytics"],["#data","Member data"]].map(([url,label]) => <Link key={url} className="rounded-full border border-ridge px-4 py-2 hover:border-signal" href={url}>{label}</Link>)}</nav>
    <section id="analytics" className="grid gap-4 sm:grid-cols-3">{[["Members checked in","64","Distinct booking holders"],["Repeat travellers","38%","24 returned for another trip"],["Cancellations","6%","5 of 83 bookings · sample data"]].map(([label,value,hint]) => <article key={label} className="rounded-panel border border-ridge bg-basalt p-6"><p className="text-sm text-lichen">{label}</p><p className="my-3 text-4xl font-bold text-signal">{value}</p><p className="text-xs text-lichen">{hint}</p></article>)}</section>
    <div className="grid gap-6 lg:grid-cols-2"><section id="access" className="rounded-panel border border-ridge bg-basalt p-6"><h2 className="text-xl font-bold">The right tools for each organiser</h2><p className="mt-3 text-sm text-lichen">Finance handles accounts. Leaders coordinate assigned trips. Moderators care for feedback.</p><h3 className="mt-5 font-semibold">Sample trip leader</h3><AccessEditor member={{ id: "preview-member", staffRole: "LEADER", tripIds: ["preview-trip"] }} trips={[{ id: "preview-trip", title: "A weekend in the hills" }, { id: "preview-trip-2", title: "Chennai nature walk" }]} /></section>
    <section id="activity" className="rounded-panel border border-ridge bg-basalt p-6"><h2 className="text-xl font-bold">Every change has a history</h2>{[["Finance organiser","Recorded a family deposit","Payment ledger · ₹2,000"],["Trip leader","Checked in two travellers","Attendance · 0 → 2"],["Administrator","Assigned a trip leader","Staff access · one departure"]].map(([who,what,detail]) => <div key={who} className="mt-5 border-l-2 border-signal/50 pl-4"><p className="text-xs text-lichen">{who} · sample event</p><p className="mt-1 font-semibold">{what}</p><p className="mt-1 text-sm text-lichen">{detail}</p></div>)}</section></div>
    <section id="delivery" className="rounded-panel border border-ridge p-6"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">Keep the next traveller informed</h2><span className="rounded-full bg-signal/10 px-3 py-1 text-xs text-signal">Waitlist → confirmed → notification</span></div><p className="mt-3 max-w-3xl text-sm text-lichen">Promotion notices queue automatically. Email and opted-in WhatsApp delivery are tracked separately. Uncertain delivery is held for review, protecting members from repeat messages.</p><div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-ridge bg-basalt p-4"><p className="font-bold">Email · QUEUED</p><p className="mt-2 text-sm text-lichen">Sample family · 3 confirmed places</p></div><div className="rounded-xl border border-ridge bg-basalt p-4"><p className="font-bold">WhatsApp · REVIEW_REQUIRED</p><DeliveryRetry id="preview-delivery" /></div></div></section>
    <section id="data"><MemberDataControls optIn={false} number={null} /></section>
  </main></div></div>;
}
