import Link from "next/link";
import { requireAdmin } from "@/lib/session";
import { prisma } from "@/lib/prisma";
import { gmailConfigured } from "@/lib/gmail";
import { formatINR, formatDateTime } from "@/lib/format";

export default async function ReportsPage() {
  await requireAdmin();
  const [trips, deliveries, tripMessages] = await Promise.all([
    prisma.trip.findMany({ orderBy: { startDate: "desc" }, take: 100, include: { paymentEvents: { select: { amount: true } }, expenses: { select: { amount: true } }, responses: { select: { overall: true, followUpStatus: true } }, registrations: { select: { partySize: true, checkedInCount: true } } } }),
    prisma.birthdayDelivery.findMany({ orderBy: { sentAt: "desc" }, take: 100 }),
    prisma.tripMessageDelivery.findMany({ orderBy: { createdAt: "desc" }, take: 100 }),
  ]);
  return <main id="main" className="container space-y-8 py-12"><h1 className="text-3xl font-bold">Reports & delivery</h1>
    <section className="rounded-panel border border-ridge p-6"><h2 className="text-xl font-bold">Email configuration</h2><p className="mt-3">{gmailConfigured() && process.env.CRON_SECRET ? "Gmail and scheduler credentials are configured. Delivery still needs a controlled test." : "Automatic birthday email is inactive until Gmail credentials and CRON_SECRET are added in Vercel."}</p><p className="mt-2 text-sm text-lichen">Sender: sanchari.chn@gmail.com. A delivery marked REVIEW_REQUIRED or SENDING needs checking in Gmail before retrying; uncertain deliveries are never automatically resent.</p></section>
    <section><h2 className="text-xl font-bold">Trip reports</h2><p className="mt-2 text-sm text-lichen">Latest 100 trips. Receipts include only ledger entries; historical payment labels are not counted as money received. Attendance counts travellers, feedback counts responses.</p><div className="mt-4 grid gap-4 md:grid-cols-2">{trips.map((trip) => { const net = trip.paymentEvents.reduce((sum,p) => sum + Number(p.amount),0); const expenses = trip.expenses.reduce((sum,e) => sum + Number(e.amount),0); return <article key={trip.id} className="rounded-panel border border-ridge p-5"><Link className="font-bold text-signal" href={`/admin/trips/${trip.id}`}>{trip.title}</Link><dl className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><dt>Net receipts</dt><dd>{formatINR(net)}</dd></div><div><dt>Expenses</dt><dd>{formatINR(expenses)}</dd></div><div><dt>Receipts less expenses</dt><dd>{formatINR(net-expenses)}</dd></div><div><dt>Checked in</dt><dd>{trip.registrations.reduce((n,r) => n+r.checkedInCount,0)}</dd></div><div><dt>Feedback average</dt><dd>{trip.responses.length ? (trip.responses.reduce((n,r) => n+r.overall,0)/trip.responses.length).toFixed(1) + "/5" : "No responses"}</dd></div><div><dt>Open follow-ups</dt><dd>{trip.responses.filter((r) => r.followUpStatus !== "RESOLVED").length}</dd></div></dl><a className="mt-3 inline-block text-sm underline" href={`/admin/trips/${trip.id}/payments.csv`}>Download ledger</a></article>; })}</div></section>
    <section><h2 className="text-xl font-bold">Birthday delivery history</h2><div className="mt-3 space-y-2">{deliveries.length ? deliveries.map((delivery) => <div key={delivery.id} className="rounded-lg border border-ridge p-3 text-sm"><span className="font-semibold">{delivery.status}</span> · {delivery.recipientKey.split(":").slice(1).join(":")} · {formatDateTime(delivery.sentAt)}</div>) : <p className="text-lichen">No delivery attempts recorded.</p>}</div></section>
    <section><h2 className="text-xl font-bold">Trip communication history</h2><p className="mt-2 text-sm text-lichen">{process.env.TRIP_EMAILS_ENABLED === "true" ? "Trip reminders enabled." : "Trip reminders disabled. Set TRIP_EMAILS_ENABLED=true after Gmail is tested."} Payment reminders run three days before departure; briefings one day before; feedback requests one day after, if the feedback form is open.</p><div className="mt-3 space-y-2">{tripMessages.map((message) => <p key={message.id} className="rounded-lg border border-ridge p-3 text-sm">{message.status} · {message.kind} · {message.recipient} · {formatDateTime(message.createdAt)}</p>)}</div></section>
  </main>;
}
