import Link from "next/link";
import { requireAdmin } from "@/lib/session";
import { prisma } from "@/lib/prisma";
export default async function ActivityPage({ searchParams }: { searchParams: { cursor?: string; entity?: string; actor?: string } }) {
  await requireAdmin();
  const where = { ...(searchParams.entity ? { entity: searchParams.entity.slice(0, 60) } : {}), ...(searchParams.actor ? { actorId: searchParams.actor.slice(0, 100) } : {}) };
  const logs = await prisma.activityLog.findMany({ where, orderBy: [{ createdAt: "desc" }, { id: "desc" }], take: 51, ...(searchParams.cursor ? { cursor: { id: searchParams.cursor }, skip: 1 } : {}) });
  const people = await prisma.user.findMany({ where: { id: { in: logs.flatMap(l => l.actorId ? [l.actorId] : []) } }, select: { id: true, name: true } });
  const names = new Map(people.map(p => [p.id, p.name]));
  const params = new URLSearchParams({ ...(searchParams.entity ? { entity: searchParams.entity } : {}), ...(searchParams.actor ? { actor: searchParams.actor } : {}), cursor: logs[49]?.id ?? "" });
  return <main id="main" className="container space-y-6 py-12"><h1 className="text-3xl font-bold">Activity history</h1><p className="text-lichen">Changes recorded from this release onward. Sensitive personal fields are redacted; before and after values show other changes. Anonymous feedback does not identify its author.</p><form className="flex flex-wrap gap-3"><label>Record type<input className="ml-2 rounded border border-ridge bg-basalt p-2" name="entity" defaultValue={searchParams.entity} placeholder="trip, paymentEvent, user…" /></label><label>Actor ID<input className="ml-2 rounded border border-ridge bg-basalt p-2" name="actor" defaultValue={searchParams.actor} /></label><button className="rounded bg-signal px-4 text-black">Filter</button></form>{logs.slice(0,50).map(l => <article key={l.id} className="rounded-panel border border-ridge p-5"><p className="font-bold">{names.get(l.actorId ?? "") ?? (l.actorId ? "Former member" : "System / anonymous submission")} · {l.operation} · {l.entity}</p><p className="break-all text-xs text-lichen">{l.createdAt.toISOString()} · Record {l.entityId ?? "multiple"} · Actor {l.actorId ?? "none"}</p>{l.changedFields.length > 0 && <p className="mt-2 break-words text-sm text-lichen">Fields: {l.changedFields.join(", ")}</p>}<details className="mt-3"><summary className="cursor-pointer text-signal">View change</summary><div className="mt-3 grid gap-4 md:grid-cols-2"><div><h3>Before</h3><pre className="max-h-80 overflow-auto whitespace-pre-wrap break-all text-xs">{JSON.stringify(l.before,null,2)}</pre></div><div><h3>After</h3><pre className="max-h-80 overflow-auto whitespace-pre-wrap break-all text-xs">{JSON.stringify(l.after,null,2)}</pre></div></div></details></article>)}{!logs.length && <p>No changes recorded yet.</p>}{logs.length > 50 && <Link className="text-signal underline" href={"/admin/activity?"+params}>Older changes →</Link>}</main>;
}
