import { requireAdmin } from "@/lib/session";
import { prisma } from "@/lib/prisma";
import { gmailConfigured } from "@/lib/gmail";
import { whatsappConfigured } from "@/lib/whatsapp";
import { DeliveryRetry } from "@/components/admin/governance-controls";
export default async function NotificationsPage() {
  await requireAdmin();
  const [messages, counts] = await Promise.all([prisma.notification.findMany({ orderBy: { createdAt: "desc" }, take: 100 }), prisma.notification.groupBy({ by: ["status"], _count: true })]);
  return <main id="main" className="container space-y-6 py-12"><h1 className="text-3xl font-bold">Notifications</h1><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-panel border border-ridge bg-basalt p-5"><h2 className="font-bold">Email promotions</h2><p className="text-signal">{gmailConfigured() && process.env.TRIP_EMAILS_ENABLED === "true" ? "Configured" : "Waiting for Gmail configuration / enablement"}</p></div><div className="rounded-panel border border-ridge bg-basalt p-5"><h2 className="font-bold">WhatsApp Business</h2><p className="text-signal">{whatsappConfigured() ? "Configured; delivery requires approved template" : "Waiting for Meta credentials and approved template"}</p></div></div><p className="text-lichen">Promotions are queued automatically when seats become available. The daily trip-message job processes up to 20 queued messages at 05:00 UTC (10:30 AM IST); an external scheduler can call /api/cron/notifications more frequently. WhatsApp requires member opt-in. Uncertain deliveries require provider review before retrying.</p><div className="flex flex-wrap gap-4">{counts.map(c => <p key={c.status}>{c.status}: <strong>{c._count}</strong></p>)}</div>{messages.map(m => <article key={m.id} className="rounded-panel border border-ridge p-4"><h2 className="font-bold">{m.channel} · {m.status}</h2><p className="break-all text-sm text-lichen">{m.kind} · {m.createdAt.toISOString()} · Member {m.userId}</p><p className="text-sm">{m.error}</p>{["FAILED", "REVIEW_REQUIRED"].includes(m.status) && <DeliveryRetry id={m.id} />}</article>)}{!messages.length && <p>No waitlist promotions queued yet.</p>}</main>;
}
