import { requireAdmin } from "@/lib/session";
import { prisma } from "@/lib/prisma";
import { repeatMemberMetrics, cancellationRate } from "@/lib/member-analytics";
export default async function AnalyticsPage({ searchParams }: { searchParams: { months?: string } }) {
  await requireAdmin();
  const months = [3,6,12,24].includes(Number(searchParams.months)) ? Number(searchParams.months) : 12;
  const since = new Date(); since.setUTCMonth(since.getUTCMonth()-months);
  const trips = await prisma.trip.findMany({ where: { startDate: { gte: since } }, select: { id: true, title: true, startDate: true, registrations: { select: { userId: true, tripId: true, checkedInCount: true, user: { select: { deletedAt: true } } } } }, orderBy: { startDate: "desc" } });
  const cancellations = await prisma.cancellation.findMany({ where: { tripId: { in: trips.map(t => t.id) } } });
  const metrics = repeatMemberMetrics(trips.flatMap(t => t.registrations.filter(r => r.checkedInCount > 0 && !r.user.deletedAt)));
  const total = trips.reduce((n,t) => n+t.registrations.length,0);
  return <main id="main" className="container space-y-6 py-12"><h1 className="text-3xl font-bold">Member & cancellation analytics</h1><form className="flex flex-wrap gap-3"><label>Departures since<select name="months" defaultValue={months} className="ml-3 rounded border border-ridge bg-basalt p-2">{[3,6,12,24].map(m => <option value={m} key={m}>{m} months ago</option>)}</select></label><button className="rounded bg-signal px-4 text-black">Apply</button></form><div className="grid gap-4 md:grid-cols-3">{[["Members checked in", metrics.members],["Repeat members", `${metrics.repeat} · ${metrics.rate.toFixed(1)}%`],["Recorded cancellations", `${cancellations.length} · ${cancellationRate(total,cancellations.length).toFixed(1)}%`]].map(([label,value]) => <article key={label} className="rounded-panel border border-ridge bg-basalt p-6"><p className="text-sm text-lichen">{label}</p><p className="mt-3 text-3xl font-bold text-signal">{value}</p></article>)}</div><p className="max-w-3xl text-sm text-lichen">Repeat members are booking holders with recorded check-in on at least two distinct departures in this period; family members are not counted separately. Deleted accounts are excluded. Cancellation rate is recorded cancelled bookings divided by current bookings plus recorded cancellations, for these departures. Cancellation tracking starts with this release; older cancellations cannot be reconstructed. Missing historical check-ins reduce repeat-member counts.</p><section className="space-y-3"><h2 className="text-xl font-bold">By departure</h2>{trips.map(t => { const events = cancellations.filter(c => c.tripId === t.id); return <article key={t.id} className="rounded-panel border border-ridge p-5"><h3 className="font-bold">{t.title}</h3><p className="mt-2 text-sm text-lichen">{t.startDate.toLocaleDateString("en-IN")} · {t.registrations.length} current bookings · {events.length} cancellations ({events.reduce((n,c) => n+c.partySize,0)} travellers) · {events.filter(c => c.wasConfirmed).length} previously confirmed · {cancellationRate(t.registrations.length,events.length).toFixed(1)}%</p></article>; })}{!trips.length && <p>No departures in this period.</p>}</section></main>;
}
