import Link from "next/link";

const trips = [{ title: "Jawadhu Hills · Forest camp", date: "18–20 Oct 2026", seats: "18/24 seats", unpaid: 3, gear: 5, consent: 1, status: "OPEN" }, { title: "Yelagiri sunrise trek", date: "02 Nov 2026", seats: "11/16 seats", unpaid: 0, gear: 2, consent: 0, status: "WAITLIST" }];

export default function ControlRoomPreview() {
  return <main className="container py-10 md:py-14"><p className="text-sm text-signal">Local preview</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-4xl font-black">Trip control room</h1><p className="mt-2 text-lichen">Run every departure from one place.</p></div><Link href="/admin/trips" className="rounded-full border border-ridge px-4 py-2 text-sm">All trips →</Link></div><dl className="mt-10 grid grid-cols-2 gap-px overflow-hidden rounded-panel border border-ridge bg-ridge md:grid-cols-4"><Stat label="Members" value="248" /><Stat label="Upcoming trips" value="6" /><Stat label="Seats not fully paid" value="7" warn /><Stat label="Gear checks to do" value="14" warn /></dl><section className="mt-10"><h2 className="text-xl font-bold">Needs attention</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Alert label="Unpaid seats" value="7" /><Alert label="Gear checks" value="14" /><Alert label="Open departures" value="6" /><Alert label="Birthday wishes" value="View" /></div></section><section className="mt-12"><h2 className="text-xl font-bold">Departure readiness</h2><div className="mt-5 grid gap-4 lg:grid-cols-2">{trips.map((trip) => <article key={trip.title} className="rounded-panel border border-ridge bg-basalt p-5"><div className="flex items-start justify-between gap-4"><div><h3 className="font-semibold">{trip.title}</h3><p className="mt-1 text-sm text-lichen">{trip.date}</p></div><span className="rounded-full border border-signal/50 px-3 py-1 text-xs text-signal">{trip.status}</span></div><div className="mt-5 flex flex-wrap gap-2 text-xs"><Pill label={trip.seats} good /><Pill label={`${trip.unpaid} unpaid`} good={!trip.unpaid} /><Pill label={`${trip.gear} gear`} good={!trip.gear} /><Pill label={`${trip.consent} consent`} good={!trip.consent} /></div></article>)}</div></section></main>;
}
function Stat({ label, value, warn }: { label: string; value: string; warn?: boolean }) { return <div className="bg-basalt p-5"><dt className="text-sm text-lichen">{label}</dt><dd className={`mt-2 text-4xl font-bold ${warn ? "text-signal" : "text-mist"}`}>{value}</dd></div>; }
function Alert({ label, value }: { label: string; value: string }) { return <div className="rounded-panel border border-ridge bg-basalt p-4"><p className="text-sm text-lichen">{label}</p><p className="mt-2 text-3xl font-bold text-signal">{value}</p><p className="mt-1 text-xs text-lichen">Open queue →</p></div>; }
function Pill({ label, good }: { label: string; good: boolean }) { return <span className={`rounded-full border px-3 py-1 ${good ? "border-emerald-400/40 text-emerald-200" : "border-signal/60 text-signal"}`}>{good ? "✓ " : "! "}{label}</span>; }
